version: '3'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    hostname: mariadb
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=mysmilepro
      - MARIADB_PASSWORD=8Nx344GAsZXV
      - MARIADB_DATABASE=mysmilepro
      - MARIADB_ROOT_PASSWORD=Pd886GNYYJUR
      - MARIADB_PORT=3305
    ports:
      - '3305:3305'
    volumes:
      - mysql:/bitnami/mariadb
  mysmilepro-old:
    hostname: mysmilepro
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_USER=mysmilepro
      - MARIADB_PASSWORD=8Nx344GAsZXV
      - MARIADB_DATABASE=mysmilepro
      - MARIADB_PORT=3306
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11210
    build:
      context: ./old
      dockerfile: Dockerfile
    ports:
      - '8082:80'
      #- '443:443'
    volumes:
      - ./old/MySmilePro:/var/www/html/MySmilePro
  mysmilepro-new:
    hostname: mysmilepro
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_USER=mysmilepro
      - MARIADB_PASSWORD=8Nx344GAsZXV
      - MARIADB_DATABASE=mysmilepro
      - MARIADB_PORT=3306
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11210
    build:
      context: ./new
      dockerfile: Dockerfile
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./new/MySmilePro:/var/www/html/MySmilePro
    depends_on:
      - mariadb
      - memcached

  memcached:
    container_name: memcached
    image: memcached:latest
    environment:
      - MEMCACHED_PORT_NUMBER=11210
    ports:
      - "11210:11210"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80

volumes:
  mysql:
